name: c2s-challenge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cars
    ports:
      - "5433:5432"
    networks:
      - app_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cars"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: .
    command: python main.py --server
    environment:
      DB_TYPE: postgresql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cars
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5555:5555"  # Expose ZMQ se necessário
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge